const languageObj = {
  en: {
    searchText: "Search",
    placeHolder: "What would you like to watch?",
    list: "My List",
    search: "Search",
    home: "Home",
    signIn: "Sign In",
    signOut: "Sign Out",
    trendingMovies: "Trending Movies",
    series: "Series",
    popularMovies: "Popular Movies",
    topRated: "Top Rated",
    play: "Play",
    moreInfo: "More Info",
  },
  hindi: {
    searchText: "खोजें",
    placeHolder: "आप क्या देखना चाहेंगे?",
    list: "मेरी सूची",
    search: "खोजें",
    home: "होम",
    signIn: "साइन इन करें",
    signOut: "साइन आउट करें",
    trendingMovies: "लोकप्रिय फिल्में",
    series: "सीरीज़",
    popularMovies: "लोकप्रिय फिल्में",
    topRated: "शीर्ष रेटेड",
    play: "प्ले करें",
    moreInfo: "और जानकारी",
  },
  spanish: {
    searchText: "Buscar",
    placeHolder: "¿Qué te gustaría ver?",
    list: "Mi Lista",
    search: "Buscar",
    home: "Inicio",
    signIn: "Iniciar sesión",
    signOut: "Cerrar sesión",
    trendingMovies: "Películas de Tendencia",
    series: "Series",
    popularMovies: "Películas Populares",
    topRated: "Mejor Calificadas",
    play: "Reproducir",
    moreInfo: "Más información",
  },
  german: {
    searchText: "Suche",
    placeHolder: "Was möchtest du sehen?",
    list: "Meine Liste",
    search: "Suche",
    home: "Startseite",
    signIn: "Anmelden",
    signOut: "Abmelden",
    trendingMovies: "Trending Filme",
    series: "Serien",
    popularMovies: "Beliebte Filme",
    topRated: "Top Bewertet",
    play: "Abspielen",
    moreInfo: "Mehr Info",
  },
};

export default languageObj;
