const languageObj = {
  en: {
    searchText: "Search",
    placeHolder: "What would you like to watch?",
    list: "My List",
    search: "Search",
    home: "Home",
    signIn: "Sign In",
    signOut: "Sign Out",
    trendingMovies: "Trending Movies",
    series: "Series",
    popularMovies: "Popular Movies",
    topRated: "Top Rated",
    play: "Play",
    moreInfo: "More Info",
    email: "Email",
    password: "Password",
    netflix_text: "New to Netflix?",
    signUpNow: "Sign Up Now",
    signUp: "Sign Up",
    fullName: "Full Name",
    alreadyExists: "Already Exists?",
    SignInNow: "Sign In Now",
  },
  hindi: {
    searchText: "खोजें",
    placeHolder: "आप क्या देखना चाहेंगे?",
    list: "मेरी सूची",
    search: "खोजें",
    home: "होम",
    signIn: "साइन इन करें",
    signOut: "साइन आउट करें",
    trendingMovies: "लोकप्रिय फिल्में",
    series: "सीरीज़",
    popularMovies: "लोकप्रिय फिल्में",
    topRated: "शीर्ष रेटेड",
    play: "प्ले करें",
    moreInfo: "और जानकारी",
    email: "ईमेल",
    password: "पासवर्ड",
    netflix_text: "Netflix का नया सदस्य?",
    signUpNow: "अभी साइन अप करें",
    signUp: "साइन अप करें",
    fullName: "पूरा नाम",
    alreadyExists: "पहले से मौजूद है?",
    SignInNow: "अब साइन इन करें",
  },
  spanish: {
    searchText: "Buscar",
    placeHolder: "¿Qué te gustaría ver?",
    list: "Mi Lista",
    search: "Buscar",
    home: "Inicio",
    signIn: "Iniciar sesión",
    signOut: "Cerrar sesión",
    trendingMovies: "Películas de Tendencia",
    series: "Series",
    popularMovies: "Películas Populares",
    topRated: "Mejor Calificadas",
    play: "Reproducir",
    moreInfo: "Más información",
    email: "Correo electrónico",
    password: "Contraseña",
    netflix_text: "¿Nuevo en Netflix?",
    signUpNow: "Regístrate ahora",
    signUp: "Registrarse",
    fullName: "Nombre completo",
    alreadyExists: "Ya existe?",
    SignInNow: "Inicia sesión ahora",
  },
  german: {
    searchText: "Suche",
    placeHolder: "Was möchst du sehen?",
    list: "Meine Liste",
    search: "Suche",
    home: "Startseite",
    signIn: "Anmelden",
    signOut: "Abmelden",
    trendingMovies: "Trending Filme",
    series: "Serien",
    popularMovies: "Beliebte Filme",
    topRated: "Top Bewertet",
    play: "Abspielen",
    moreInfo: "Mehr Info",
    email: "E-Mail",
    password: "Passwort",
    netflix_text: "Neu bei Netflix?",
    signUpNow: "Jetzt registrieren",
    signUp: "Registrieren",
    fullName: "Vollständiger Name",
    alreadyExists: "Bereits vorhanden?",
    SignInNow: "Jetzt anmelden",
  },
};


export default languageObj;
